name: ATXcursions
markdown: redcarpet
pygments: true

picture:
  source: images
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 1200px)"
        width: 700
      source_med:
        media: "(min-width: 992px)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      source_lrg:
        media: "(min-width: 1200px)"
        width: 400
      source_med:
        media: "(min-width: 992px)"
        width: 250
      source_default:
        width: 350
    # Right aligned
    right:
      ppi: [1, 1.5]
      attr:
        class: pull-right col-xs-12
      source_lrg:
        media: "(min-width: 1200px)"
        width: 400
      source_med:
        media: "(min-width: 992px)"
        width: 250
      source_default:
        width: 350
    # Logo
    logo:
      source_default:
        width: 200
    # Self-set resolution sources.
    gallery:
      attr:
        class: "pull-right col-xs-12 rounded"
      source_wide_hi:
        media: "(min-width: 1200px)"
        width: 1200
      source_lrg:
        media: "(min-width: 992px)"
        width: 900
      source_med:
        media: "(min-width: 768px)"
        width: 700
      source_default:
        width: 500
